<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>false</UseWindowsForms>
    <RootNamespace>Helion.Client</RootNamespace>

    <AssemblyName>Helion</AssemblyName>
    <ApplicationIcon>helion.ico</ApplicationIcon>

    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(SelfContainedRelease)' == 'true'">
    <SelfContained>True</SelfContained>
    <PublishSingleFile>True</PublishSingleFile>
    <PublishReadyToRun>True</PublishReadyToRun>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>

  <PropertyGroup Condition="'$(AOT)' == 'true'">
    <PublishAot>true</PublishAot>
    <OptimizationPreference>Speed</OptimizationPreference>
    <!-- See https://github.com/dotnet/runtime/blob/main/src/coreclr/nativeaot/docs/optimizing.md for instruction set info -->
    <!-- x86-x64-v3: Haswell and newer (~2013) with FMA and AVX2.  x86-64-v4: AVX-512 required. -->
    <!--<IlcInstructionSet>x86-x64-v3</IlcInstructionSet>-->

    <!-- Avoid copying symbols for release AOT builds, as these are miserable to debug even with symbols (and the files are huge) -->
    <CopyOutputSymbolsToPublishDirectory Condition="'$(Configuration)'=='Release'">false</CopyOutputSymbolsToPublishDirectory>
    <AllowedReferenceRelatedFileExtensions Condition="'$(Configuration)'=='Release'">none</AllowedReferenceRelatedFileExtensions>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Helion.SDLControllerWrapper" Version="3.0.0.2" />
    <PackageReference Include="Helion.GLFW" Version="3.4.0.1" />
    <PackageReference Include="Helion.OpenALSoft" Version="1.25.2.1" />
  </ItemGroup>

  <ItemGroup Condition="'$(AOT)' == 'true'">
    <DirectPInvoke Include="zmusic.dll" />
    <DirectPInvoke Include="glfw3.dll" />
    <DirectPInvoke Include="SDL2.dll" />
    <DirectPInvoke Include="AL" />
    <DirectPInvoke Include="HelionACS-native" />
  </ItemGroup>

  <ItemGroup Condition="('$(AOT)' == 'true') AND ('$(RuntimeIdentifier)'=='win-x64')">
    <!-- These are all .libs that would normally get included if we were building DLLs from one or more of our native deps using CMake;
    All of these come from the Windows SDK, e.g. C:\Program Files (x86)\Windows Kits\10\Lib\10.0.26100.0\um\x64 -->
    <LinkerArg Include="Gdi32.lib" />
    <LinkerArg Include="WinSpool.lib" />
    <LinkerArg Include="shell32.lib" />
    <LinkerArg Include="Uuid.lib" />
    <LinkerArg Include="ComDlg32.lib" />
    <LinkerArg Include="avrt.lib" />
    <LinkerArg Include="WinMM.lib" />
    <LinkerArg Include="Imm32.lib" />
    <LinkerArg Include="Shlwapi.lib" />
    <LinkerArg Include="Setupapi.lib" />
  </ItemGroup>

  <ItemGroup Condition="('$(AOT)' == 'true') AND ('$(RuntimeIdentifier)'=='linux-x64')">
    <LinkerArg Include="-lstdc++" />
    <LinkerArg Include="-lsndfile" />
    <LinkerArg Include="-lmpg123" />
    <LinkerArg Include="-lasound" />
    <LinkerArg Include="-lglib-2.0" />
  </ItemGroup>

  <Target Name="HandleNativeLibraries" BeforeTargets="ResolveLockFileCopyLocalFiles">
    <ItemGroup Condition="('$(AOT)' == 'true')">
      <NativeLibrary Include="@(NativeCopyLocalItems)" Condition="('%(Extension)'=='.lib') AND ('$(RuntimeIdentifier)'=='win-x64')" />
      <NativeLibrary Include="@(NativeCopyLocalItems)" Condition="('%(Extension)'=='.a') AND ('$(RuntimeIdentifier)'=='linux-x64')" />

      <!-- Don't copy shared libs if we're doing an AOT build, we are doing static linking here -->
      <RuntimeTargetsCopyLocalItems Remove="@(RuntimeTargetsCopyLocalItems)" />
      <NativeCopyLocalItems Remove="@(NativeCopyLocalItems)" />
    </ItemGroup>

    <!-- Ensure that we never propagate .lib or .a files to the output directory; nobody's going to need those for anything other than native linking -->
    <ItemGroup>
      <RuntimeTargetsCopyLocalItems Remove="@(RuntimeTargetsCopyLocalItems)" Condition="'%(Extension)'=='.lib'" />
      <RuntimeTargetsCopyLocalItems Remove="@(RuntimeTargetsCopyLocalItems)" Condition="'%(Extension)'=='.a'" />
      <NativeCopyLocalItems Remove="@(NativeCopyLocalItems)" Condition="'%(Extension)'=='.lib'" />
      <NativeCopyLocalItems Remove="@(NativeCopyLocalItems)" Condition="'%(Extension)'=='.a'" />
    </ItemGroup>
  </Target>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <WarningLevel>0</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="SoundFonts\*" />

    <Content Include="helion.ico" Link="%(Filename)%(Extension)" CopyToOutputDirectory="Never" />
    <Content Include="$(HelionRootDir)Assets\Documentation\README.md" Link="%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="$(ProjectDir)SoundFonts\*" Link="SoundFonts\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>

  <Target Name="SetPublishDir" BeforeTargets="Build">
    <PropertyGroup>
      <PublishDir Condition="'$(SelfContainedRelease)' == 'true'">$(HelionRootDir)\Publish\$(RuntimeIdentifier)_SelfContained\</PublishDir>
      <PublishDir Condition="'$(AOT)' == 'true'">$(HelionRootDir)\Publish\$(RuntimeIdentifier)_AOT\</PublishDir>
      <PublishDir Condition="'$(SelfContainedRelease)' != 'true' AND '$(AOT)' != 'true'">$(HelionRootDir)\Publish\$(RuntimeIdentifier)\</PublishDir>
    </PropertyGroup>
  </Target>

  <Target Name="GetAssetsIncludeFiles">
    <ItemGroup>
      <AssetSources Include="$(HelionRootDir)Assets\Assets\**\*" />
    </ItemGroup>
  </Target>

  <Target Name="MakeAssetsFile" AfterTargets="Build" DependsOnTargets="GetAssetsIncludeFiles" Inputs="@(AssetSources)" Outputs="$(TargetDir)\assets.pk3">
    <ZipDirectory SourceDirectory="$(HelionRootDir)Assets\Assets" DestinationFile="$(TargetDir)\assets.pk3" Overwrite="true" />
  </Target>

  <Target Name="CopyAssetsFileAfterPublish" AfterTargets="Publish" Inputs="$(TargetDir)\assets.pk3" Outputs="$(PublishDir)\assets.pk3">
    <Copy SourceFiles="$(TargetDir)\assets.pk3" DestinationFiles="$(PublishDir)\assets.pk3" SkipUnchangedFiles="true" />
  </Target>

  <Target Name="GetFilesForPostPublishCopy" DependsOnTargets="PublishItemsOutputGroup">
    <ItemGroup>
      <PostPublishFiles Include="@(Content)" Destination="$(PublishDir)%(Link)" Condition="'%(CopyToOutputDirectory)' != 'Never'" />
      <!-- Deal with an annoying case where redoing a single-file publish deletes openal32.dll and some other native files -->
      <PostPublishFiles Include="@(NativeCopyLocalItems)" Destination="$(PublishDir)%(NativeCopyLocalItems.DestinationSubPath)" />
    </ItemGroup>
  </Target>

  <Target Name="EnsureContentFilesAfterPublish" AfterTargets="Publish" DependsOnTargets="GetFilesForPostPublishCopy" Inputs="@(PostPublishFiles)" Outputs="@(PostPublishFiles -> '%(Destination)')">
    <Copy SourceFiles="@(PostPublishFiles)" DestinationFiles="%(Destination)" SkipUnchangedFiles="true" />
  </Target>
</Project>
