using Helion.Util;
using Helion.Util.Container;
using Helion.Util.RandomGenerators;
using Helion.World.Entities;
using Helion.World.Entities.Definition;
using Helion.World.Entities.Definition.States;
using Helion.World.Physics.Blockmap;
using Helion.World.Sound;
using System.Collections.Generic;

namespace Helion.World;

public static class WorldStatic
{
    public static DynamicArray<BlockmapIntersect> Intersections = new(1024);
    public static IWorld World = null!;
    public static IRandom Random = null!;
    public static DataCache DataCache = null!;
    public static int CheckCounter = 1;
    public static int SlowTickDistance;
    public static int RespawnTicks;
    public static int ClosetLookFrameIndex;
    public static int ClosetChaseFrameIndex;
    public static short SlowTickChaseFailureSkipCount;
    public static short SlowTickChaseMultiplier;
    public static short SlowTickLookMultiplier;
    public static short SlowTickTracerMultiplier;
    public static bool SlowTickEnabled;
    public static bool IsFastMonsters;
    public static bool IsSlowMonsters;
    public static bool InfinitelyTallThings;
    public static bool MissileClip;
    public static bool AllowItemDropoff;
    public static bool NoTossDrops;
    public static bool VanillaMovementPhysics;
    public static bool Dehacked;
    public static bool Mbf21;
    public static bool Doom2ProjectileWalkTriggers;
    public static bool OriginalExplosion;
    public static bool FinalDoomTeleport;
    public static bool VanillaSectorSound;
    public static bool Udmf;
    public static bool SectorFriction;
    public static bool BloodColor;
    public static bool MirrorCorpse;
    public static bool Sector3D;
    public static bool MbfTelefrag;
    public static EntityManager EntityManager = null!;
    public static WorldSoundManager SoundManager = null!;
    public static List<EntityFrame> Frames = null!;
    public static int[] CheckedLines = [];
    public static double LineVertexGap;
    public static double LineVertexGapTopZ;
    public static double LineVertexGapBottomZ;
    public static float LineVertexOffset;
    public static float CoverWallOffset;
    public static float DamageApplyMultiplier = 1;
    public static float DamageReceiveMultiplier = 1;
    public static int MaxSoulsphere = 200;

    public static EntityDefinition DoomImpBall = EntityDefinition.Default;
    public static EntityDefinition ArachnotronPlasma = EntityDefinition.Default;
    public static EntityDefinition Rocket = EntityDefinition.Default;
    public static EntityDefinition FatShot = EntityDefinition.Default;
    public static EntityDefinition CacodemonBall = EntityDefinition.Default;
    public static EntityDefinition RevenantTracer = EntityDefinition.Default;
    public static EntityDefinition RevenantTracerSmoke = EntityDefinition.Default;
    public static EntityDefinition BaronBall = EntityDefinition.Default;
    public static EntityDefinition SpawnShot = EntityDefinition.Default;
    public static EntityDefinition BFGBall = EntityDefinition.Default;
    public static EntityDefinition BFGExtra = EntityDefinition.Default;
    public static EntityDefinition PlasmaBall = EntityDefinition.Default;
    public static EntityDefinition BulletPuff = EntityDefinition.Default;
    public static EntityDefinition ArchvileFire = EntityDefinition.Default;
    public static EntityDefinition LostSoul = EntityDefinition.Default;
    public static EntityDefinition BossRocket = EntityDefinition.Default;
    public static EntityDefinition RealGibs = EntityDefinition.Default;

    public static EntityDefinition WeaponBfg = EntityDefinition.Default;
}
