namespace Helion.World.Entities.Definition.Flags;

public static class FlagValue
{
    public const int Flag1 = 1;
    public const int Flag2 = 1 << 1;
    public const int Flag3 = 1 << 2;
    public const int Flag4 = 1 << 3;
    public const int Flag5 = 1 << 4;
    public const int Flag6 = 1 << 5;
    public const int Flag7 = 1 << 6;
    public const int Flag8 = 1 << 7;
    public const int Flag9 = 1 << 8;
    public const int Flag10 = 1 << 9;
    public const int Flag11 = 1 << 10;
    public const int Flag12 = 1 << 11;
    public const int Flag13 = 1 << 12;
    public const int Flag14 = 1 << 13;
    public const int Flag15 = 1 << 14;
    public const int Flag16 = 1 << 15;
    public const int Flag17 = 1 << 16;
    public const int Flag18 = 1 << 17;
    public const int Flag19 = 1 << 18;
    public const int Flag20 = 1 << 19;
    public const int Flag21 = 1 << 20;
    public const int Flag22 = 1 << 21;
    public const int Flag23 = 1 << 22;
    public const int Flag24 = 1 << 23;
    public const int Flag25 = 1 << 24;
    public const int Flag26 = 1 << 25;
    public const int Flag27 = 1 << 26;
    public const int Flag28 = 1 << 27;
    public const int Flag29 = 1 << 28;
    public const int Flag30 = 1 << 29;
    public const int Flag31 = 1 << 30;
    public const int Flag32 = 1 << 31;

    public const int InvFlag1 =  ~Flag1;
    public const int InvFlag2 =  ~Flag2;
    public const int InvFlag3 =  ~Flag3;
    public const int InvFlag4 =  ~Flag4;
    public const int InvFlag5 =  ~Flag5;
    public const int InvFlag6 =  ~Flag6;
    public const int InvFlag7 =  ~Flag7;
    public const int InvFlag8 =  ~Flag8;
    public const int InvFlag9 =  ~Flag9;
    public const int InvFlag10 = ~Flag10;
    public const int InvFlag11 = ~Flag11;
    public const int InvFlag12 = ~Flag12;
    public const int InvFlag13 = ~Flag13;
    public const int InvFlag14 = ~Flag14;
    public const int InvFlag15 = ~Flag15;
    public const int InvFlag16 = ~Flag16;
    public const int InvFlag17 = ~Flag17;
    public const int InvFlag18 = ~Flag18;
    public const int InvFlag19 = ~Flag19;
    public const int InvFlag20 = ~Flag20;
    public const int InvFlag21 = ~Flag21;
    public const int InvFlag22 = ~Flag22;
    public const int InvFlag23 = ~Flag23;
    public const int InvFlag24 = ~Flag24;
    public const int InvFlag25 = ~Flag25;
    public const int InvFlag26 = ~Flag26;
    public const int InvFlag27 = ~Flag27;
    public const int InvFlag28 = ~Flag28;
    public const int InvFlag29 = ~Flag29;
    public const int InvFlag30 = ~Flag30;
    public const int InvFlag31 = ~Flag31;
    public const int InvFlag32 = ~Flag32;
}

