<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.2" />
    <PackageReference Include="Microsoft.VisualStudio.DiagnosticsHub.BenchmarkDotNetDiagnosers" Version="18.7.37220.1" />
  </ItemGroup>
  <ItemGroup>
	<ProjectReference Include="..\Core\Core.csproj" />
	<ProjectReference Include="..\Tests\Tests.csproj" />
  </ItemGroup>
  <ItemGroup>
	<None Update="Resources\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
