<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    
    <Nullable>enable</Nullable>
    <NullableContextOptions>enable</NullableContextOptions>
    <NullableReferenceTypes>true</NullableReferenceTypes>
  </PropertyGroup>
</Project>
