namespace Helion.Resources
{
    public enum ResourceType
    {
        Behavior,
        Blockmap,
        Decorate,
        Directory,
        GLMapMarker,
        GLNodes,
        GLPVS,
        GLSegments,
        GLSubsectors,
        GLVertices,
        Linedefs,
        Image,
        Marker,
        Nodes,
        Palette,
        PaletteImage,
        Pk3,
        Pnames,
        Reject,
        Scripts,
        Sectors,
        Segs,
        Sidedefs,
        Subsectors,
        Things,
        Text,
        TextureX,
        TrueTypeFont,
        Unknown,
        Vertexes,
        Wad
    }
}
