namespace Helion.Resources.Definitions.StatusBar.Enums;

public enum StatusBarConditionType
{
    WeaponOwned = 0,
    WeaponSelected = 1,
    WeaponNotSelected = 2,
    WeaponHasAmmo = 3,
    SelectedWeaponHasAmmo = 4,
    AmmoMatch = 5,
    SlotOwned = 6,
    SlotNotOwned = 7,
    SlotSelected = 8,
    SlotNotSelected = 9,
    ItemOwned = 10,
    ItemNotOwned = 11,
    GameVersionGe = 12,
    GameVersionLt = 13,
    SessionTypeEq = 14,
    SessionTypeNeq = 15,
    GameModeEq = 16,
    GameModeNeq = 17,
    HudModeEq = 18,
    
    // v1.1 Extensions
    AutomapModeEq = 19,
    WidgetEnabled = 20,
    WidgetDisabled = 21,
    WeaponNotOwned = 22,
    HealthGe = 23,
    HealthLt = 24,
    HealthPercentGe = 25,
    HealthPercentLt = 26,
    ArmorGe = 27,
    ArmorLt = 28,
    ArmorPercentGe = 29,
    ArmorPercentLt = 30,
    SelectedAmmoGe = 31,
    SelectedAmmoLt = 32,
    SelectedAmmoPercentGe = 33,
    SelectedAmmoPercentLt = 34,
    AmmoGe = 35,
    AmmoLt = 36,
    AmmoPercentGe = 37,
    AmmoPercentLt = 38,
    WidescreenModeEq = 39,
    EpisodeEq = 40,
    LevelGe = 41,
    LevelLt = 42,
    
    // v1.2
    PatchEmpty = 43,
    PatchNotEmpty = 44,
    KillsLt = 45,
    KillsGe = 46,
    ItemsLt = 47,
    ItemsGe = 48,
    SecretsLt = 49,
    SecretsGe = 50,
    KillsPercentLt = 51,
    KillsPercentGe = 52,
    ItemsPercentLt = 53,
    ItemsPercentGe = 54,
    SecretsPercentLt = 55,
    SecretsPercentGe = 56,
    PowerupDurationLt = 57,
    PowerupDurationGe = 58,
    PowerupDurationPercentLt = 59,
    PowerupDurationPercentGe = 60
}