using System.Collections.Generic;

namespace Helion.World.Special.Specials;

public static class ThingSpawnTypes
{
    public static readonly Dictionary<int, string> Lookup = new()
    {
        { 0, "NONE" },
        { 1, "SHOTGUNGUY" },
        { 2, "CHAINGUY" },
        { 3, "BARON" },
        { 4, "ZOMBIEMAN" },
        { 5, "DOOMIMP" },
        { 6, "ARACHNOTRON" },
        { 7, "SPIDERMASTERMIND" },
        { 8, "DEMON" },
        { 9, "SPECTRE" },
        { 10, "DOOMIMPBALL" },
        { 11, "CLIP" },
        { 12, "SHELLS" },
        { 19, "CACODEMON" },
        { 20, "REVENANT" },
        { 21, "BRIDGE" },
        { 22, "ARMORBONUS" },
        { 23, "STIMPACK" },
        { 24, "MEDKIT" },
        { 25, "SOULSPHERE" },
        { 27, "SHOTGUN" },
        { 28, "CHAINGUN" },
        { 29, "ROCKETLAUNCHER" },
        { 30, "PLASMAGUN" },
        { 31, "BFG" },
        { 32, "CHAINSAW" },
        { 33, "SUPERSHOTGUN" },
        { 51, "PLASMABOLT" },
        { 53, "TRACER" },
        { 68, "GREENARMOR" },
        { 69, "BLUEARMOR" },
        { 75, "CELL" },
        { 85, "BLUECARD" },
        { 86, "REDCARD" },
        { 87, "YELLOWCARD" },
        { 88, "YELLOWSKULL" },
        { 89, "REDSKULL" },
        { 90, "BLUESKULL" },
        { 98, "TEMPLARGEFLAME" },
        { 100, "STEALTHBARON" },
        { 101, "STEALTHKNIGHT" },
        { 102, "STEALTHZOMBIE" },
        { 103, "STEALTHSHOTGUY" },
        { 110, "LOSTSOUL" },
        { 111, "ARCHVILE" },
        { 112, "MANCUBUS" },
        { 113, "HELLKNIGHT" },
        { 114, "CYBERDEMON" },
        { 115, "PAINELEMENTAL" },
        { 116, "WOLFSS" },
        { 117, "STEALTHARACHNOTRON" },
        { 118, "STEALTHVILE" },
        { 119, "STEALTHCACODEMON" },
        { 120, "STEALTHCHAINGUY" },
        { 121, "STEALTHSERGEANT" },
        { 122, "STEALTHIMP" },
        { 123, "STEALTHMANCUBUS" },
        { 124, "STEALTHREVENANT" },
        { 125, "BARREL" },
        { 126, "CACODEMONBALL" },
        { 127, "ROCKET" },
        { 128, "BFGSHOT" },
        { 129, "ARACHNOTRONPLASMA" },
        { 130, "BLOOD" },
        { 131, "PUFF" },
        { 132, "MEGASPHERE" },
        { 133, "INVULNERABILITY" },
        { 134, "BERSERK" },
        { 135, "INVISIBILITY" },
        { 136, "IRONFEET" },
        { 137, "COMPUTERMAP" },
        { 138, "LIGHTAMP" },
        { 139, "AMMOBOX" },
        { 140, "ROCKETAMMO" },
        { 141, "ROCKETBOX" },
        { 142, "BATTERY" },
        { 143, "SHELLBOX" },
        { 144, "BACKPACK" },
        { 145, "GUTS" },
        { 146, "BLOODPOOL" },
        { 147, "BLOODPOOL1" },
        { 148, "BLOODPOOL2" },
        { 149, "FLAMINGBARREL" },
        { 150, "BRAINS" },
        { 151, "SCRIPTEDMARINE" },
        { 152, "HEALTHBONUS" },
        { 153, "MANCUBUSSHOT" },
        { 154, "BARONBALL" }
    };

}
