using System.Collections.Generic;

namespace Helion.World.Special.Specials;

public static class ThingSpawnTypes
{
    public static readonly Dictionary<int, string> Lookup = new()
    {
        { 0, "NONE" },
        { 1, "SHOTGUNGUY" },
        { 2, "ChaingunGuy" },
        { 3, "BaronOfHell" },
        { 4, "ZOMBIEMAN" },
        { 5, "DOOMIMP" },
        { 6, "ARACHNOTRON" },
        { 7, "SPIDERMASTERMIND" },
        { 8, "DEMON" },
        { 9, "SPECTRE" },
        { 10, "DOOMIMPBALL" },
        { 11, "CLIP" },
        { 12, "Shell" },
        { 19, "CACODEMON" },
        { 20, "REVENANT" },
        { 21, "InvisibleBridge32" },
        { 22, "ARMORBONUS" },
        { 23, "STIMPACK" },
        { 24, "Medikit" },
        { 25, "SOULSPHERE" },
        { 27, "SHOTGUN" },
        { 28, "CHAINGUN" },
        { 29, "ROCKETLAUNCHER" },
        { 30, "PlasmaRifle" },
        { 31, "BFG9000" },
        { 32, "CHAINSAW" },
        { 33, "SUPERSHOTGUN" },
        { 51, "PlasmaBall" },
        { 53, "RevenantTracerSmoke" },
        { 68, "GREENARMOR" },
        { 69, "BLUEARMOR" },
        { 75, "CELL" },
        { 85, "BLUECARD" },
        { 86, "REDCARD" },
        { 87, "YELLOWCARD" },
        { 88, "YELLOWSKULL" },
        { 89, "REDSKULL" },
        { 90, "BLUESKULL" },
        { 98, "TEMPLARGEFLAME" },
        { 100, "StealthBaron" },
        { 101, "StealthHellKnight" },
        { 102, "StealthZombieMan" },
        { 103, "StealthShotgunGuy" },
        { 110, "LOSTSOUL" },
        { 111, "ARCHVILE" },
        { 112, "Fatso" },
        { 113, "HELLKNIGHT" },
        { 114, "CYBERDEMON" },
        { 115, "PAINELEMENTAL" },
        { 116, "WolfensteinSS" },
        { 117, "StealthArachnotron" },
        { 118, "StealthArchvile" },
        { 119, "StealthCacodemon" },
        { 120, "StealthChaingunGuy" },
        { 121, "StealthDemon" },
        { 122, "StealthDoomImp" },
        { 123, "StealthFatso" },
        { 124, "StealthRevenant" },
        { 125, "ExplosiveBarrel" },
        { 126, "CACODEMONBALL" },
        { 127, "ROCKET" },
        { 128, "BFGBall" },
        { 129, "ARACHNOTRONPLASMA" },
        { 130, "BLOOD" },
        { 131, "BulletPuff" },
        { 132, "MEGASPHERE" },
        { 133, "InvulnerabilitySphere" },
        { 134, "BERSERK" },
        { 135, "BlurSphere" },
        { 136, "RadSuit" },
        { 137, "Allmap" },
        { 138, "Infrared" },
        { 139, "ClipBox" },
        { 140, "ROCKETAMMO" },
        { 141, "ROCKETBOX" },
        { 142, "CellPack" },
        { 143, "SHELLBOX" },
        { 144, "BACKPACK" },
        { 145, "GibbedMarine" },
        { 146, "Gibs" },
        { 147, "ColonGibs" },
        { 148, "SmallBloodPool" },
        { 149, "FLAMINGBARREL" },
        { 150, "BrainStem" },
        { 151, "SCRIPTEDMARINE" },
        { 152, "HEALTHBONUS" },
        { 153, "FATSHOT" },
        { 154, "BARONBALL" }
    };
}
