using FluentAssertions;
using Helion.Dehacked;
using Xunit;

namespace Helion.Tests.Unit.Dehacked;

public class DehackedText
{
    [Fact(DisplayName = "Dehacked text")]
    public void DehackedTextBlock()
    {
        string data = @"
Doom version = 19
Patch format = 6


Text 405 303
YOU HAVE ENTERED DEEPLY INTO THE INFESTED
STARPORT. BUT SOMETHING IS WRONG. THE
MONSTERS HAVE BROUGHT THEIR OWN REALITY
WITH THEM, AND THE STARPORT'S TECHNOLOGY
IS BEING SUBVERTED BY THEIR PRESENCE.

AHEAD, YOU SEE AN OUTPOST OF HELL, A
FORTIFIED ZONE. IF YOU CAN GET PAST IT,
YOU CAN PENETRATE INTO THE HAUNTED HEART
OF THE STARBASE AND FIND THE CONTROLLING
SWITCH WHICH HOLDS EARTH'S POPULATION
HOSTAGE.YOU STEPPED THROUGH ENOUGH LAVA TO COOK
YOUR BOOTS TO A NICE MEDIUM RARE. YOU
ARE ALREADY EXCITED FOR THE NICE COOL
BATH YOU HAVE PREPARED BACK AT HOME.
";
        var dehacked = new DehackedDefinition();
        dehacked.Parse(data);

        dehacked.Strings.Count.Should().Be(1);
        var str = dehacked.Strings[0];
        str.OldString.Should().Be("YOU HAVE ENTERED DEEPLY INTO THE INFESTED\nSTARPORT. BUT SOMETHING IS WRONG. THE\nMONSTERS HAVE BROUGHT THEIR OWN REALITY\nWITH THEM, AND THE STARPORT'S TECHNOLOGY\nIS BEING SUBVERTED BY THEIR PRESENCE.\n\nAHEAD, YOU SEE AN OUTPOST OF HELL, A\nFORTIFIED ZONE. IF YOU CAN GET PAST IT,\nYOU CAN PENETRATE INTO THE HAUNTED HEART\nOF THE STARBASE AND FIND THE CONTROLLING\nSWITCH WHICH HOLDS EARTH'S POPULATION\nHOSTAGE.");
        str.NewString.Should().Be("YOU STEPPED THROUGH ENOUGH LAVA TO COOK\nYOUR BOOTS TO A NICE MEDIUM RARE. YOU\nARE ALREADY EXCITED FOR THE NICE COOL\nBATH YOU HAVE PREPARED BACK AT HOME.");
    }
}
