namespace Helion.World.Entities.Players
{
    public enum TickCommands
    {
        None,
        Forward,
        Backward,
        Left,
        Right,
        TurnLeft,
        TurnRight,
        LookUp,
        LookDown,
        Attack,
        Jump,
        Crouch,
        Use,
        Speed,
        Strafe,
        NextWeapon,
        PreviousWeapon,
        WeaponSlot1,
        WeaponSlot2,
        WeaponSlot3,
        WeaponSlot4,
        WeaponSlot5,
        WeaponSlot6,
        WeaponSlot7,
        CenterView,
    }
}