# This workflow will build, publish, and release Helion.
# Release detail text is copied from RELEASENOTES.md.
# Release files will include source snapshots, and ZIP files with prebuilt executables for Linux and Windows (both single-file and runtime-dependent)

# Release checklist:
# 1.  Update RELEASENOTES.md
# 2.  Update version info in Directory.Build.props
# 3.  Ensure you are synced to a commit that includes the updated state of (1) and (2); run `git pull` if needed
# 4.  Create a new tag, e.g. `git tag 0.9.5.0`
# 5.  Push the new tag, e.g. `git push origin 0.9.5.0`

name: Make Tagged Release

on:
  push:
    tags:
    - '*'

jobs:
  buildRelease:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            rid: linux-x64
            prereqs: sudo apt -y install clang zlib1g libsndfile1-dev libmpg123-dev libglib2.0-dev libasound2-dev patchelf fuse file
          - os: windows-2025-vs2026
            rid: win-x64
            prereqs: echo "Hi"
          - os: macos-15
            rid: osx-arm64
            prereqs: brew install libsndfile mpg123
            
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with: 
          dotnet-version: 10.0.x
      - name: Install Prerequisites
        run: ${{ matrix.prereqs }}

      - name: Make Output Directory
        run: mkdir -p output
        
      - name: Publish Self-Contained
        run: dotnet publish -c Release -r ${{ matrix.rid }} -p:SelfContainedRelease=true
        working-directory: Client
      
      - name: Publish AOT
        run: dotnet publish -c Release -r ${{ matrix.rid }} -p:AOT=true
        working-directory: Client

      - name: Zip Build Artifacts (non-Windows)
        if: ${{ matrix.rid != 'win-x64' }}
        run: |
          cd Publish/${{ matrix.rid }}_SelfContained
          zip -r ../../output/Helion-${{ github.ref_name }}-${{ matrix.rid }}_SelfContained.zip *
          cd ../${{ matrix.rid }}_AOT
          zip -r ../../output/Helion-${{ github.ref_name }}-${{ matrix.rid }}_AOT.zip *

      - name: Zip Build Artifacts (Windows)
        if: ${{ matrix.rid == 'win-x64' }}
        run: |
          Compress-Archive -Path .\Publish\win-x64_SelfContained\* -DestinationPath output\Helion-${{ github.ref_name }}-win-x64_SelfContained.zip
          Compress-Archive -Path .\Publish\win-x64_AOT\* -DestinationPath output\Helion-${{ github.ref_name }}-win-x64_AOT.zip
      
      - name: Make Additional packages (Linux)
        if: ${{ matrix.rid == 'linux-x64' }}
        run: |
          Scripts/buildAndPackageAppImage.sh
          mv Helion.AppImage output/Helion-${{ github.ref_name }}.AppImage
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{matrix.rid}}
          path: output
          
  PublishRelease:
    runs-on: ubuntu-22.04
    needs: buildRelease
    steps:
      - uses: actions/checkout@v7
      - name: Get Build Artifacts
        uses: actions/download-artifact@v8
        with: 
          path: output
          merge-multiple: true
      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
            artifacts: "output/*"
            bodyFile: "RELEASENOTES.md"
