# This workflow will build, publish, and release Helion.
# Release detail text is copied from RELEASENOTES.md.
# Release files will include source snapshots, and ZIP files with prebuilt executables for Linux and Windows (both single-file and runtime-dependent)

# Release checklist:
# 1.  Update RELEASENOTES.md
# 2.  Update version info in Directory.Build.props
# 3.  Ensure you are synced to a commit that includes the updated state of (1) and (2); run `git pull` if needed
# 4.  Create a new tag, e.g. `git tag 0.9.5.0`
# 5.  Push the new tag, e.g. `git push origin 0.9.5.0`

name: Make .NET Release

on:
  push:
    tags:
    - '*'

jobs:
  buildReleaseLinux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Install Linux prereqs
      run: sudo apt -y install clang zlib1g libsndfile1-dev libmpg123-dev libglib2.0-dev libasound2-dev patchelf fuse file
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
    - name: Dotnet Publish Linux
      run: dotnet publish -c Release -r linux-x64 Client/Client.csproj -p:SelfContainedRelease=true
    - name: Dotnet Publish Linux AOT
      run: dotnet publish -c Release -r linux-x64 Client/Client.csproj -p:AOT=true
      
    - name: Zip Linux Self-Contained
      run: zip -r ../../Helion-${{ github.ref_name }}-linux-x64_SelfContained.zip *
      working-directory: Publish/linux-x64_SelfContained
    - name: Zip Linux AOT
      run: zip -r ../../Helion-${{ github.ref_name }}-linux-x64_AOT.zip *
      working-directory: Publish/linux-x64_AOT
      
    - name: Make Linux AppImage
      run: Scripts/buildAndPackageAppImage.sh
    
    - name: Make Linux DEB
      run: Scripts/buildAndPackageDeb.sh ${{ github.ref_name }}
      
    - name: Make Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "*.zip,Helion.AppImage,Helion*.deb"
        bodyFile: "RELEASENOTES.md"
  
  buildReleaseWindows:
    runs-on: windows-2025-vs2026
    needs: buildReleaseLinux

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
    - name: Dotnet Publish Windows
      run: dotnet publish -c Release -r win-x64 Client/Client.csproj -p:SelfContainedRelease=true
    - name: Dotnet Publish Windows AOT
      run: dotnet publish -c Release -r win-x64 Client/Client.csproj -p:AOT=true
      
    - name: Zip Windows Self-Contained
      run: Compress-Archive -Path .\Publish\win-x64_SelfContained\* -DestinationPath .\Helion-${{ github.ref_name }}-win-x64_SelfContained.zip
    - name: Zip Windows AOT
      run: Compress-Archive -Path .\Publish\win-x64_AOT\* -DestinationPath .\Helion-${{ github.ref_name }}-win-x64_AOT.zip

    - name: Add binaries to release (Windows)
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: '*.zip'
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
